name: Capture screenshots

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1" # Mondays 13:00 UTC (~9:00 AM ET)

jobs:
  capture:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (Playwright)
        run: npm ci

      - name: Capture screenshots
        run: npm run capture

      - name: Upload screenshots artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ github.run_id }}
          path: out/**
